version:  '2.0'

services:
      non-hospital-client:
            container_name: non-hospital-client
            expose:
                  - 3000
            ports:
                  - 3002:3000
            build:
                  context: ./non-hospital-client
            volumes:
                  - '.:/prm'

      hospital-client:
            container_name: hospital-client
            expose:
                  - 3000
            ports:
                  - 3001:3000
            build:
                  context: ./hospital-client
            volumes:
                  - '.:/prm'
      patient-client:
            container_name: patient-client
            expose:
                  - 3000
            ports:
                  - 3000:3000
            build:
                  context: ./patient-client
            volumes:
                  - '.:/prm'
      processor:
            container_name: processor
            build:
                  context: ./processor
            depends_on:
                  - validator
            volumes:
                  - ".:/prm"

      # events:
      #       container_name: events
      #       build:
      #             context: ./events
      #       expose:
      #             - 80
      #       ports:
      #             - '80:80'
      #       depends_on:
      #             - validator
      #       volumes:
      #             - '.:/prm'
                  
      sawtooth-rest-api:
            container_name: rest-api
            image: hyperledger/sawtooth-rest-api:1.0
            expose:
                  - 8008
            ports:
                  - '8008:8008'
            depends_on:
                  - validator
            entrypoint: |
                  sawtooth-rest-api -vvv
                  --connect tcp://validator:4004
                  --bind sawtooth-rest-api:8008

      settings-tp:
            container_name: settings-tp
            image: hyperledger/sawtooth-settings-tp:1.0
            depends_on:
                  - validator
            command: settings-tp -vv --connect tcp://validator:4004
      
      identity-tp:
            container_name: identity-tp
            image: hyperledger/sawtooth-identity-tp:1.1
            depends_on:
                  - validator
            entrypoint: identity-tp -vvv -C tcp://validator:4004

      validator:
            container_name: validator
            image: hyperledger/sawtooth-validator:1.0
            expose:
                  - 4004
            ports:
                  - '4004:4004'
            command: |
                  bash -c "
                  if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
                  sawadm keygen &&
                  sawtooth keygen my_key &&
                  sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
                  sawadm genesis config-genesis.batch
                  fi;
                  sawtooth-validator -vvv \
                  --endpoint tcp://validator:8800 \
                  --bind component:tcp://eth0:4004 \
                  --bind network:tcp://eth0:8800 \
                  --scheduler parallel -vv"
